//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SIC_gramatica.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SIC_gramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ISIC_gramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] SIC_gramaticaParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] SIC_gramaticaParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInicio([NotNull] SIC_gramaticaParser.InicioContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInicio([NotNull] SIC_gramaticaParser.InicioContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.fin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFin([NotNull] SIC_gramaticaParser.FinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.fin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFin([NotNull] SIC_gramaticaParser.FinContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.linea"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinea([NotNull] SIC_gramaticaParser.LineaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.linea"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinea([NotNull] SIC_gramaticaParser.LineaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion([NotNull] SIC_gramaticaParser.InstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion([NotNull] SIC_gramaticaParser.InstruccionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion2([NotNull] SIC_gramaticaParser.Instruccion2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion2([NotNull] SIC_gramaticaParser.Instruccion2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion3([NotNull] SIC_gramaticaParser.Instruccion3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion3([NotNull] SIC_gramaticaParser.Instruccion3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion4([NotNull] SIC_gramaticaParser.Instruccion4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion4([NotNull] SIC_gramaticaParser.Instruccion4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.directiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectiva([NotNull] SIC_gramaticaParser.DirectivaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.directiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectiva([NotNull] SIC_gramaticaParser.DirectivaContext context);
}
