//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SIC_gramatica.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISIC_gramaticaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SIC_gramaticaBaseListener : ISIC_gramaticaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] SIC_gramaticaParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] SIC_gramaticaParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInicio([NotNull] SIC_gramaticaParser.InicioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.inicio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInicio([NotNull] SIC_gramaticaParser.InicioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.fin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFin([NotNull] SIC_gramaticaParser.FinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.fin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFin([NotNull] SIC_gramaticaParser.FinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.linea"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinea([NotNull] SIC_gramaticaParser.LineaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.linea"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinea([NotNull] SIC_gramaticaParser.LineaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion([NotNull] SIC_gramaticaParser.InstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion([NotNull] SIC_gramaticaParser.InstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion2([NotNull] SIC_gramaticaParser.Instruccion2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion2([NotNull] SIC_gramaticaParser.Instruccion2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion3([NotNull] SIC_gramaticaParser.Instruccion3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion3([NotNull] SIC_gramaticaParser.Instruccion3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.instruccion4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion4([NotNull] SIC_gramaticaParser.Instruccion4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.instruccion4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion4([NotNull] SIC_gramaticaParser.Instruccion4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SIC_gramaticaParser.directiva"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectiva([NotNull] SIC_gramaticaParser.DirectivaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SIC_gramaticaParser.directiva"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectiva([NotNull] SIC_gramaticaParser.DirectivaContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
